remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Large MySQL Migrator
description: A PHP library for migrating large MySQL databases by splitting tables into individual ZIP files
url: "https://delhiarpitpatel.github.io"
baseurl: "/large-mysql-migrator"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Installation
    url: /installation
  - title: Usage
    url: /usage
  - title: API Reference
    url: /api
  - title: Examples
    url: /examples

# Build settings
markdown: kramdown
highlighter: rouge
